-- 1. Création de la table 'games'
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  bgg_id bigint not null unique,
  name text not null,
  thumbnail_url text,
  min_players integer,
  max_players integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Activation de la Sécurité (RLS)
-- Par défaut, Supabase bloque tout. On doit ouvrir explicitement.
alter table public.games enable row level security;

-- 3. Règles de Sécurité (Policies)
-- A. Tout le monde (connecté) peut LIRE les jeux (pour les chercher)
create policy "Enable read access for authenticated users"
  on public.games for select
  to authenticated
  using (true);

-- B. Tout le monde (connecté) peut CRÉER un jeu
-- (C'est nécessaire quand on importe un jeu depuis BGG pour la première fois)
create policy "Enable insert for authenticated users"
  on public.games for insert
  to authenticated
  with check (true);

-- C. Personne ne peut MODIFIER ou SUPPRIMER un jeu pour l'instant
-- (On protège notre bibliothèque commune)
