-- ==============================================================================
-- 🏗️ FICHIER DE RÉFÉRENCE : STRUCTURE DE LA BASE (SCHEMA)
-- Description : Crée les tables et les relations.
-- Mis à jour : Ajout table PLAYS + correction types (bigint)
-- ==============================================================================

-- 1. Table : GAMES (Bibliothèque publique des jeux)
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  bgg_id bigint not null unique,
  name text not null,
  thumbnail_url text,
  image_url text,
  description text,
  year_published integer,
  min_age integer,
  playing_time integer,
  rating numeric(3, 1),
  complexity numeric(3, 2),
  min_players integer,
  max_players integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table : CHALLENGES (Le conteneur du défi utilisateur)
create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text default 'Mon Challenge 10x10',
  year integer default 2026,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, year)
);

-- 3. Table : CHALLENGE_ITEMS (Les lignes du défi)
create table if not exists public.challenge_items (
  id bigint generated by default as identity primary key,
  challenge_id bigint references public.challenges(id) on delete cascade not null,
  game_id bigint references public.games(id) not null,
  progress integer default 0,
  target integer default 10,
  meeple_color text default 'red',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(challenge_id, game_id)
);

-- 4. Table : PLAYS (Historique des parties)
create table if not exists public.plays (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  
  -- Correction : bigint pour correspondre à la table games
  game_id bigint references public.games(id) on delete cascade not null, 
  
  played_on timestamp with time zone default now() not null,
  duration_minutes int default 0,
  player_count int default 1,
  is_victory boolean default false,
  notes text,
  
  -- Correction : Tableau de textes pour plusieurs photos
  image_urls text[] default array[]::text[],
  
  created_at timestamp with time zone default now()
);
