-- ==============================================================================
-- 🏗️ MASTER SCRIPT : MEEPLE & MILESTONES (vFinal)
-- Description : Structure, Sécurité (RLS), Triggers et Configuration Realtime
-- ==============================================================================

-- 0. NETTOYAGE (Pour repartir d'une page blanche si nécessaire)
-- Attention : Cela supprime toutes les données !
DROP TABLE IF EXISTS public.plays CASCADE;
DROP TABLE IF EXISTS public.challenge_items CASCADE;
DROP TABLE IF EXISTS public.challenges CASCADE;
DROP TABLE IF EXISTS public.games CASCADE;

-- On nettoie la publication realtime pour la recréer proprement
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime;

-- ==============================================================================
-- 1. TABLES & RELATIONS (STRUCTURE)
-- ==============================================================================

-- A. GAMES (Bibliothèque publique des jeux)
CREATE TABLE public.games (
  id bigint generated by default as identity primary key,
  bgg_id bigint not null unique,
  name text not null,
  thumbnail_url text,
  image_url text,
  description text,
  year_published integer,
  min_age integer,
  playing_time integer,
  rating numeric(3, 1),
  complexity numeric(3, 2),
  min_players integer,
  max_players integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- B. CHALLENGES (Le conteneur du défi utilisateur)
CREATE TABLE public.challenges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text default 'Mon Challenge 10x10',
  year integer default 2026,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, year)
);

-- C. CHALLENGE_ITEMS (Les jeux dans la collection de l'utilisateur)
CREATE TABLE public.challenge_items (
  id bigint generated by default as identity primary key,
  challenge_id bigint references public.challenges(id) on delete cascade not null,
  game_id bigint references public.games(id) on delete cascade not null, -- Cascade si le jeu global est supprimé
  progress integer default 0,
  target integer default 10,
  meeple_color text default 'red',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(challenge_id, game_id)
);

-- D. PLAYS (Historique des parties)
CREATE TABLE public.plays (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  -- Cascade : Si un jeu est supprimé, ses parties le sont aussi (évite les orphelins)
  game_id bigint references public.games(id) on delete cascade not null, 
  played_on timestamp with time zone default now() not null,
  duration_minutes int default 0,
  player_count int default 1,
  is_victory boolean default false,
  notes text,
  image_urls text[] default array[]::text[],
  created_at timestamp with time zone default now()
);

-- ==============================================================================
-- 2. SÉCURITÉ (ROW LEVEL SECURITY - RLS)
-- ==============================================================================

-- Activation de la sécurité sur toutes les tables
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plays ENABLE ROW LEVEL SECURITY;

-- FONCTIONS UTILITAIRES --------------------------------------------------------

-- Vérifie si l'utilisateur est propriétaire du challenge
CREATE OR REPLACE FUNCTION public.check_challenge_ownership(challenge_id bigint)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.challenges
    WHERE id = check_challenge_ownership.challenge_id
    AND user_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Création automatique du challenge à l'inscription
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.challenges (user_id, name, year)
  VALUES (new.id, 'Mon Challenge 10x10', 2026);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- TRIGGER INSCRIPTION ----------------------------------------------------------
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- POLITIQUES DE SÉCURITÉ (POLICIES) --------------------------------------------

-- 1. GAMES (Lecture publique, Modification par authentifiés)
CREATE POLICY "Games_Read_Public" ON public.games FOR SELECT USING (true);
CREATE POLICY "Games_Write_Auth" ON public.games FOR ALL USING (auth.role() = 'authenticated');

-- 2. CHALLENGES (Accès privé)
CREATE POLICY "Challenges_Select_Own" ON public.challenges FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Challenges_Insert_Own" ON public.challenges FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. CHALLENGE_ITEMS (Accès via la propriété du challenge parent)
CREATE POLICY "Items_Select_Own" ON public.challenge_items FOR SELECT USING (public.check_challenge_ownership(challenge_id));
CREATE POLICY "Items_Insert_Own" ON public.challenge_items FOR INSERT WITH CHECK (public.check_challenge_ownership(challenge_id));
CREATE POLICY "Items_Update_Own" ON public.challenge_items FOR UPDATE USING (public.check_challenge_ownership(challenge_id));
CREATE POLICY "Items_Delete_Own" ON public.challenge_items FOR DELETE USING (public.check_challenge_ownership(challenge_id));

-- 4. PLAYS (Accès privé)
CREATE POLICY "Plays_Select_Own" ON public.plays FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Plays_Insert_Own" ON public.plays FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Plays_Update_Own" ON public.plays FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Plays_Delete_Own" ON public.plays FOR DELETE USING (auth.uid() = user_id);

-- ==============================================================================
-- 3. CONFIGURATION REALTIME (CRITIQUE POUR LA NAVBAR & UI)
-- ==============================================================================

-- ⚠️ REPLICA IDENTITY FULL : Obligatoire pour recevoir les DELETE côté Frontend
ALTER TABLE public.games REPLICA IDENTITY FULL;
ALTER TABLE public.plays REPLICA IDENTITY FULL;
ALTER TABLE public.challenge_items REPLICA IDENTITY FULL;

-- Ajout des tables au canal de diffusion public
ALTER PUBLICATION supabase_realtime ADD TABLE games;
ALTER PUBLICATION supabase_realtime ADD TABLE plays;
ALTER PUBLICATION supabase_realtime ADD TABLE challenge_items;

-- Fin du script
