-- ==============================================================================
-- 🏗️ FICHIER DE RÉFÉRENCE : STRUCTURE DE LA BASE (SCHEMA)
-- Description : Crée les tables et les relations.
-- ==============================================================================

-- 1. Table : GAMES (Bibliothèque publique des jeux)
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  bgg_id bigint not null unique,
  name text not null,
  thumbnail_url text,
  min_players integer,
  max_players integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table : CHALLENGES (Le conteneur du défi utilisateur)
create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text default 'Mon Challenge 10x10',
  year integer default 2026,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, year) -- Un seul challenge par an par user
);

-- 3. Table : CHALLENGE_ITEMS (Les lignes du défi : quel jeu, quelle progression)
create table if not exists public.challenge_items (
  id bigint generated by default as identity primary key,
  challenge_id bigint references public.challenges(id) on delete cascade not null,
  game_id bigint references public.games(id) not null,
  progress integer default 0,
  target integer default 10,
  meeple_color text default 'red',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(challenge_id, game_id) -- Pas de doublon du même jeu dans le même challenge
);
